CaptureZ1BadgeSections = {
	"@Map 01 - Bomb Wall/Bomb Wall",
	"@Map 03 - Bomb Wall/Bomb Wall",
	"@Map 04 - Open Cave/Open Cave",
	"@Map 05 - Spectacle Rock Entrance/Bomb Wall",
	"@Map 07 - Bomb Wall/Bomb Wall",
	"@Map 0A - Cave 12 - White Sword/Open Cave",
	"@Map 0B - Level 5 Entrance/Open Cave",
	"@Map 0C - Lost Hills Shop/Open Cave",
	"@Map 0D - Bomb Wall/Bomb Wall",
	"@Map 0E - Cave 18 - Letter Cave/Open Cave",
	"@Map 0F - Corner Secret/Open Cave",

	"@Map 10 - Bomb Wall/Bomb Wall",
	"@Map 12 - Bomb Wall/Bomb Wall",
	"@Map 13 - Bomb Wall/Bomb Wall",
	"@Map 14 - Bomb Wall/Bomb Wall",
	"@Map 16 - Bomb Wall/Bomb Wall",
	"@Map 1A - Waterfall/Enter Waterfall",
	"@Map 1C - Lost Hills Armos/Under Armos",
	"@Map 1D - Lost Hills Warp/Push Rock",
	"@Map 1E - Bomb Wall/Bomb Wall",
	"@Map 1F - Coast Gamble/Open Cave",

	"@Map 21 - Cave 13 - Magic Sword/Push Grave",
	"@Map 22 - Level 6 Entrance/Open Cave",
	"@Map 23 - Graveyard Warp/Push Rock",
	"@Map 25 - Graveyard Shop/Open Cave",
	"@Map 26 - Bomb Wall/Bomb Wall",
	"@Map 27 - Bomb Wall/Bomb Wall",
	"@Map 28 - Burn Bush/Burn Bush",
	"@Map 2C - Monocle Rock Take Any/Bomb Wall",
	"@Map 2D - Bomb Wall/Bomb Wall",
	"@Map 2F - Raft Spot Take Any/Open Cave",

	"@Map 33 - Bomb Wall/Bomb Wall",
	"@Map 34 - Armos Shop/Under Armos",
	"@Map 37 - Level 1 Entrance/Open Cave",
	"@Map 3C - Level 2 Entrance/Open Cave",
	"@Map 3D - Upper Forest Armos/Under Armos",

	"@Map 42 - Level 7 Entrance/Use Recorder",
	"@Map 44 - Lake Shop/Open Cave",
	"@Map 45 - Level 4 Entrance/Open Cave",
	"@Map 46 - Burn Bush/Burn Bush",
	"@Map 47 - Burn Bush Take Any/Burn Bush",
	"@Map 48 - Burn Bush/Burn Bush",
	"@Map 49 - Desert Warp/Push Rock",
	"@Map 4A - Desert Shop/Open Cave",
	"@Map 4B - Burn Bush/Burn Bush",
	"@Map 4D - Burn Bush/Burn Bush",
	"@Map 4E - Lower Forest Armos/Under Armos",

	"@Map 51 - Burn Bush/Burn Bush",
	"@Map 56 - Burn Bush/Burn Bush",
	"@Map 5B - Burn Bush/Burn Bush",
	"@Map 5E - Forest Shop/Open Cave",

	"@Map 62 - Burn Bush/Burn Bush",
	"@Map 63 - Burn Bush/Burn Bush",
	"@Map 64 - Dead Woods Shop/Open Cave",
	"@Map 67 - Bomb Wall/Bomb Wall",
	"@Map 68 - Burn Bush/Burn Bush",
	"@Map 6A - Burn Bush/Burn Bush",
	"@Map 6B - Burn Bush/Burn Bush",
	"@Map 6D - Level 8 Entrance/Burn Bush",
	"@Map 6F - Coast Shop/Open Cave",

	"@Map 70 - Hint Shop/Open Cave",
	"@Map 71 - Bomb Wall/Bomb Wall",
	"@Map 74 - Level 3 Entrance/Open Cave",
	"@Map 75 - Hint Shop/Open Cave",
	"@Map 76 - Bomb Wall/Bomb Wall",
	"@Map 77 - Cave 10 - Wood Sword/Open Cave",
	"@Map 78 - Burn Bush/Burn Bush",
	"@Map 79 - South Warp/Push Rock",
	"@Map 7B - South Shore Take Any/Bomb Wall",
	"@Map 7C - Bomb Wall/Bomb Wall",
	"@Map 7D - Bomb Wall/Bomb Wall"
}

CaptureZ1BadgeCache = {}