CaptureZ3BadgeSections = {
    --"@Lumberjack House/Map Badge",
    "@Lumberjack Cave/Dropdown",
    "@Death Mountain Entry Cave/Map Badge",
    "@Death Mountain Exit Back/Map Badge",
    --"@Kakariko Fortune Teller/Map Badge",
    "@Woman Left Door/Map Badge",
    "@Woman Right Door/Map Badge",
    "@Left Snitch House/Map Badge",
    "@Right Snitch House/Map Badge",
    "@Blind's House/Map Badge",
    "@The Well/Dropdown",
    "@Chicken House/Map Badge",
    "@Grass House/Map Badge",
    "@Front Tavern/Map Badge",
    "@Kakariko Shop/Map Badge",
    "@Bomb Hut/Map Badge",
    "@Sick Kid/Map Badge",
    "@Smiths House/Map Badge",
    "@Magic Bat/Dropdown",
    "@Chest Game/Map Badge",
    "@Race House Right/Map Badge",
    "@Library/Map Badge",
    "@Forest Hideout/Dropdown",
    "@Forest Chest Game/Map Badge",
    "@Castle Secret Entrance/Dropdown",
    "@Castle Main Entrance/Map Badge",
    "@Castle Left Entrance/Map Badge",
    "@Castle Right Entrance/Map Badge",
    "@Castle Tower Entrance/Map Badge",
    "@Dam/Map Badge",
    "@Central Bonk Rocks/Map Badge",
    "@Witch's Hut/Map Badge",
    "@Waterfall Fairy/Map Badge",
    "@Sahasrala's Hut/Map Badge",
    "@Trees Fairy Cave/Map Badge",
    "@Pegs Fairy Cave/Map Badge",
    "@Eastern Palace Entrance/Map Badge",
    "@Houlihan Hole/Dropdown",
    "@Sanctuary Grave/Dropdown",
    "@North Bonk Rocks/Map Badge",
    "@King's Tomb/Map Badge",
    "@Graveyard Ledge/Map Badge",
    "@Desert Left Entrance/Map Badge",
    "@Desert Back Entrance/Map Badge",
    "@Desert Right Entrance/Map Badge",
    "@Desert Front Entrance/Map Badge",
    "@Aginah's Cave/Map Badge",
    "@Thief Cave/Map Badge",
    "@Rupee Cave/Map Badge",
    "@Skull Woods Bush Hole/Dropdown",
    "@Skull Woods Left Hole/Dropdown",
    "@Skull Woods Right Hole/Dropdown",
    "@Skull Woods Front/Map Badge",
    "@Skull Woods Mid Right/Map Badge",
    "@Skull Woods Mid Left/Map Badge",
    "@Skull Woods Back Hole/Dropdown",
    "@Skull Woods Back/Map Badge",
    "@Thieves Town Entrance/Map Badge",
    "@C-Shaped House/Map Badge",
    "@Hammer House/Map Badge",
    "@Dark Village Fortune Teller/Map Badge",
    "@Dark Sanctuary/Map Badge",
    "@Shield Shop/Map Badge",
    "@Dark Lumberjack/Map Badge",
    "@Treasure Game/Map Badge",
    "@Brewery/Map Badge",
    "@Hammer Pegs/Map Badge",
    "@Bumper Cave Exit/Map Badge",
    "@Bumper Cave Entry/Map Badge",
    "@Hype Cave/Map Badge",
    "@Swamp Palace Entrance/Map Badge",
    "@Dark Central Bonk Rocks/Map Badge",
    "@South of Grove/Map Badge",
    "@Bomb Shop/Map Badge",
    "@Arrow Game/Map Badge",
    "@Race House Left/Map Badge",
    "@Dark Hylia Fortune Teller/Map Badge",
    "@Dark Trees Fairy Cave/Map Badge",
    "@Dark Saha/Map Badge",
    "@Palace of Darkness Entrance/Map Badge",
    "@Dark Witch's Hut/Map Badge",
    "@Dark Pegs Cave/Map Badge",
    "@Pyramid Fairy/Map Badge",
    "@Ganon Hole/Dropdown",
    "@Dark Ice Rod Cave/Map Badge",
    --"@Dark Fake Ice Rod Cave/Map Badge",
    "@Dark Ice Rod Rock/Map Badge",
    "@Hype Fairy Cave/Map Badge",
    --"@Fortune Teller/Map Badge",
    "@Lake Shop/Map Badge",
    "@Upgrade Fairy/Map Badge",
    "@Mini Moldorm Cave/Map Badge",
    "@Ice Rod Cave/Map Badge",
    "@Good Bee Cave/Map Badge",
    "@Ice Thief Cave/Map Badge",
    "@Ice Palace Entrance/Map Badge",
    "@Misery Mire Entrance/Map Badge",
    "@Left Mire Shack/Map Badge",
    --"@Right Mire Shack/Map Badge",
    "@Mire Cave/Map Badge",
    "@Checkerboard Cave/Map Badge",
    "@Death Mountain Entry Cave/Map Badge",
    "@Old Man Residence/Map Badge",
    --"@Old Man Back Residense/Map Badge",
    "@Death Mountain Exit Front/Map Badge",
    "@Spectacle Rock Left/Map Badge",
    "@Spectacle Rock Right/Map Badge",
    "@Spectacle Rock Top/Map Badge",
    "@Tower of Hera Entrance/Map Badge",
    "@Spiral Cave Bottom/Map Badge",
    "@EDM Fairy Cave/Map Badge",
    "@Paradox Cave Middle/Map Badge",
    "@Paradox Cave Bottom/Map Badge",
    "@EDM Connector Bottom/Map Badge",
    "@Spiral Cave Top/Map Badge",
    "@Mimic Cave/Map Badge",
    "@EDM Connector Top/Map Badge",
    "@Paradox Cave Top/Map Badge",
    "@Spike Cave/Map Badge",
    "@Dark Mountain Fairy/Map Badge",
    "@Super-Bunny Cave Bottom/Map Badge",
    "@Death Mountain Shop/Map Badge",
    "@Super-Bunny Cave Top/Map Badge",
    "@Hookshot Cave/Map Badge",
    "@Turtle Rock Entrance/Map Badge",
    "@Ganon's Tower Entrance/Map Badge",
    "@TR Ledge Left/Map Badge",
    "@TR Ledge Right/Map Badge",
    "@TR Safety Door/Map Badge",
    "@Hookshot Cave Top/Map Badge"        
}

CaptureZ3BadgeCache = {}